"""Add event_datetime to timeline

Revision ID: 1602ee70f6e9
Revises: 836f23434fd6
Create Date: 2026-05-26 19:47:52.886553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1602ee70f6e9'
down_revision: Union[str, None] = '836f23434fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_events', sa.Column('event_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_events', 'event_datetime')
    # ### end Alembic commands ###
